apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 91.7.0
    helm:
      releaseName: kps
      valuesObject:
        alertmanager:
          enabled: false
        kubeEtcd:
          enabled: false
        kubeScheduler:
          enabled: false
        kubeControllerManager:
          enabled: false
        kubeProxy:
          enabled: false
        grafana:
          admin:
            existingSecret: grafana-admin
          resources:
            requests: {cpu: 50m, memory: 256Mi}
            limits: {memory: 768Mi}
        prometheus:
          prometheusSpec:
            retention: 2d
            resources:
              requests: {cpu: 100m, memory: 400Mi}
              limits: {memory: 1Gi}
            serviceMonitorSelectorNilUsesHelmValues: false
            podMonitorSelectorNilUsesHelmValues: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
