apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo-monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/CynepMyx/k8s-lab.git
    targetRevision: main
    path: apps/podinfo-monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
